obstacle_range: 2.5
raytrace_range: 3.0

# footprint: [[front left corner], [front right corner], 
#             [rear right corner], [rear left corner]]
footprint:[[0.31, -0.30], [0.31, 0.30], [-0.31, 0.30], [-0.31, -0.30]]

inflation_radius: 0.55

observation sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: sara_lidar, data_type: LaserScan, topic: /scan, marking: true, clearing:true}
