local_costmap:
  global_frame: /odom
  robot_base_frame: sara_base
  update_frequency: 5.0
  publish_frequency: 0.5
  static_map: true
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
